import profile from './download.png'
import sujay from './sujay.png'
import sujal from './sujal.jpg'
import mayank from './mayank.jpg'
import shaswat from './shaswat.jpg'
import saurabh from './saurabh.jpg'
import aman from './aman.jpg'
import aakash from './aakash.jpg'
import mohit from './mohit.jpg'
import devashish from './devashish.jpg'
import priyanshu from './priyanshu.jpg'
import rudra from './Rudra.jpg'
import akshat from './akshat.jpg'
import aryan from './aryan.jpg'
import ashutosh from './ashutosh.jpg'
import pranjal from './pranjal.jpg'
import ankit from './ankit.jpg'
import anshuman from './anshuman.jpg'
import abhinandan from './abhinandan.jpg'
import keshav from './keshav.jpg'
import saket from './saket.jpg'

export { profile, sujay, sujal, mayank, shaswat, saurabh, aman, aakash, mohit, devashish, priyanshu, rudra, akshat, aryan, ashutosh, pranjal, ankit, anshuman, abhinandan, keshav, saket }